# Example minor-embedding

In [1]:
import numpy as np
from matplotlib import pyplot as plt

In [2]:
from qutip import *
from scipy import *

Let's consider the following embedding process
<img src="embedding.png" width="500" height="340">

with embedding values                            
<img src="values.png" width="400" height="340">

and
<img src="values2.png" width="500" height="340">

We will study the spectrum of  the hamiltonian $$ H = \sum_i h_i \sigma^z_i + \sum_{i<j} J_{ij} \sigma^z_i \sigma^z_j$$ to check if the two graphs are equivalent. 

In [3]:
def operators(N):
    si = qeye(2) #identity
    sz = sigmaz() #sigma z

    sz_list = []

    for n in range(N):
        aux_list = []
        for m in range(N):
            aux_list.append(si)
    
        aux_list[n] = sz
        sz_list.append(tensor(aux_list))
    
    return sz_list

In [4]:
def Hamiltonian(N, sz_list, Q):
    
    #H1
    H1 = 0
    for n in range(N):
        H1 += Q[n][n]*sz_list[n]

    #H2
    H2 = 0
    for n in range(N-1):
        for m in range(n+1, N):
            H2 += Q[n][m]*sz_list[n]*sz_list[m]
        
    H = H1 + H2
    
    return H

## Logical graph

In [5]:
#Parameters
N = 3 #number of qubits (spins)
dim = int(2**N) #dimension of the space
Q = np.zeros((N,N))
for i in range(N):
    Q[i][i] = -1 #qubit bias
    for j in range(N):
        if (j != i):
            Q[i][j] = 2 #coupler strengths
sz_list = operators(N)
print(Q)

[[-1.  2.  2.]
 [ 2. -1.  2.]
 [ 2.  2. -1.]]


In [6]:
#Hamiltonian
H = Hamiltonian(N, sz_list, Q)
print(H)

Quantum object: dims = [[2, 2, 2], [2, 2, 2]], shape = (8, 8), type = oper, isherm = True
Qobj data =
[[ 3.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -3.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -3.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -3.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  9.]]


In [7]:
H.eigenstates()

(array([-3., -3., -3., -1., -1., -1.,  3.,  9.]),
 array([Quantum object: dims = [[2, 2, 2], [1, 1, 1]], shape = (8, 1), type = ket
        Qobj data =
        [[0.]
         [1.]
         [0.]
         [0.]
         [0.]
         [0.]
         [0.]
         [0.]]                                                                   ,
        Quantum object: dims = [[2, 2, 2], [1, 1, 1]], shape = (8, 1), type = ket
        Qobj data =
        [[0.]
         [0.]
         [1.]
         [0.]
         [0.]
         [0.]
         [0.]
         [0.]]                                                                   ,
        Quantum object: dims = [[2, 2, 2], [1, 1, 1]], shape = (8, 1), type = ket
        Qobj data =
        [[0.]
         [0.]
         [0.]
         [0.]
         [1.]
         [0.]
         [0.]
         [0.]]                                                                   ,
        Quantum object: dims = [[2, 2, 2], [1, 1, 1]], shape = (8, 1), type = ket
        Qobj data =

## Physical graph

In [8]:
#Parameters
N = 4 #number of qubits (spins)
dim = int(2**N) #dimension of the space
Q = np.zeros((N,N))
Q[0][0] = -1
Q[1][1] = 1
Q[2][2] = 1
Q[3][3] = -1
Q[1][2] = -3
Q[2][1] = -3
Q[0][1] = 2
Q[1][0] = 2
Q[0][3] = 2
Q[3][0] = 2
Q[2][3] = 2
Q[3][2] = 2
sz_list = operators(N)
print(Q)

[[-1.  2.  0.  2.]
 [ 2.  1. -3.  0.]
 [ 0. -3.  1.  2.]
 [ 2.  0.  2. -1.]]


In [9]:
#Hamiltonian
H = Hamiltonian(N, sz_list, Q)
print(H)

Quantum object: dims = [[2, 2, 2, 2], [2, 2, 2, 2]], shape = (16, 16), type = oper, isherm = True
Qobj data =
[[ 3.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -3.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  3.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  5.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  3.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -3.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -9.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -7.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. -3.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -3.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  7.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  5.  0.  0.  0.]
 [ 0.  0.  0.  0.  

In [10]:
H.eigenstates()

(array([-9., -7., -7., -3., -3., -3., -3., -1.,  3.,  3.,  3.,  3.,  5.,
         5.,  7.,  7.]),
 array([Quantum object: dims = [[2, 2, 2, 2], [1, 1, 1, 1]], shape = (16, 1), type = ket
        Qobj data =
        [[0.]
         [0.]
         [0.]
         [0.]
         [0.]
         [0.]
         [1.]
         [0.]
         [0.]
         [0.]
         [0.]
         [0.]
         [0.]
         [0.]
         [0.]
         [0.]]                                                                          ,
        Quantum object: dims = [[2, 2, 2, 2], [1, 1, 1, 1]], shape = (16, 1), type = ket
        Qobj data =
        [[0.]
         [0.]
         [0.]
         [0.]
         [0.]
         [0.]
         [0.]
         [1.]
         [0.]
         [0.]
         [0.]
         [0.]
         [0.]
         [0.]
         [0.]
         [0.]]                                                                          ,
        Quantum object: dims = [[2, 2, 2, 2], [1, 1, 1, 1]], shape = (16, 1), type =

## Results

For the logical graph we have:
-  -3: $|001 \rangle$, $|010 \rangle$, $|100 \rangle$
-  -1: $|011 \rangle$, $|101 \rangle$, $|110 \rangle$
-  +3: $|000 \rangle$
-  +9: $|111 \rangle$

For the physical graph we have:
-  -9: $|0110 \rangle (\mathbf{|010 \rangle})$
-  -7: $|0111 \rangle (\mathbf{|011 \rangle})$, $|1110 \rangle(\mathbf{|110 \rangle})$
-  -3: $|0101 \rangle$, $|0001 \rangle (\mathbf{|001 \rangle})$, $|1000 \rangle (\mathbf{|100 \rangle})$, $|1010 \rangle$
-  -1: $|1001 \rangle (\mathbf{|101 \rangle})$
-  +3: $|0100 \rangle$, $|0000 \rangle (\mathbf{|000 \rangle})$, $|0010 \rangle$, $|1111 \rangle (\mathbf{|111 \rangle})$
-  ...

# Other Values

## Logical graph

In [11]:
#Parameters
N = 3 #number of qubits (spins)
dim = int(2**N) #dimension of the space
Q = np.zeros((N,N))
#qubit bias
Q[0][0] = 3
Q[1][1] = 0
Q[2][2] = 0
#coupler strengths
Q[0][1] = -2
Q[1][0] = -2
Q[0][2] = -2
Q[2][0] = -2
Q[1][2] = 1
Q[2][1] = 1

print(Q)

sz_list = operators(N)

[[ 3. -2. -2.]
 [-2.  0.  1.]
 [-2.  1.  0.]]


In [12]:
#Hamiltonian
H = Hamiltonian(N, sz_list, Q)
print(H)

Quantum object: dims = [[2, 2, 2], [2, 2, 2]], shape = (8, 8), type = oper, isherm = True
Qobj data =
[[ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  2.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  2.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  8.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  2.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -4.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -4.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -6.]]


In [13]:
H.eigenstates()

(array([-6., -4., -4.,  0.,  2.,  2.,  2.,  8.]),
 array([Quantum object: dims = [[2, 2, 2], [1, 1, 1]], shape = (8, 1), type = ket
        Qobj data =
        [[0.]
         [0.]
         [0.]
         [0.]
         [0.]
         [0.]
         [0.]
         [1.]]                                                                   ,
        Quantum object: dims = [[2, 2, 2], [1, 1, 1]], shape = (8, 1), type = ket
        Qobj data =
        [[0.]
         [0.]
         [0.]
         [0.]
         [0.]
         [1.]
         [0.]
         [0.]]                                                                   ,
        Quantum object: dims = [[2, 2, 2], [1, 1, 1]], shape = (8, 1), type = ket
        Qobj data =
        [[0.]
         [0.]
         [0.]
         [0.]
         [0.]
         [0.]
         [1.]
         [0.]]                                                                   ,
        Quantum object: dims = [[2, 2, 2], [1, 1, 1]], shape = (8, 1), type = ket
        Qobj data =

## Physical graph

In [14]:
#Parameters
N = 4 #number of qubits (spins)
dim = int(2**N) #dimension of the space
Q = np.zeros((N,N))
Q[0][0] = 3
Q[1][1] = 3
Q[2][2] = 0
Q[3][3] = 0
Q[1][2] = -2
Q[2][1] = -2
Q[0][1] = -3
Q[1][0] = -3
Q[0][3] = -2
Q[3][0] = -2
Q[2][3] = 1
Q[3][2] = 1
sz_list = operators(N)
print(Q)

[[ 3. -3.  0. -2.]
 [-3.  3. -2.  0.]
 [ 0. -2.  0.  1.]
 [-2.  0.  1.  0.]]


In [15]:
#Hamiltonian
H = Hamiltonian(N, sz_list, Q)
print(H)

Quantum object: dims = [[2, 2, 2, 2], [2, 2, 2, 2]], shape = (16, 16), type = oper, isherm = True
Qobj data =
[[  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.]
 [  0.   2.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.]
 [  0.   0.   2.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.]
 [  0.   0.   0.   8.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.]
 [  0.   0.   0.   0.   4.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.]
 [  0.   0.   0.   0.   0.   6.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.]
 [  0.   0.   0.   0.   0.   0.  -2.   0.   0.   0.   0.   0.   0.   0.
    0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   4.   0.   0.   0.   0.   0.   0.
    0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   4.   0.   0.   0.   0.   0.
    0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.  -2.   0.   0.   0.   0.
    0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0

In [16]:
H.eigenstates()

(array([-12., -10., -10.,  -4.,  -2.,  -2.,   0.,   2.,   2.,   4.,   4.,
          4.,   4.,   6.,   6.,   8.]),
 array([Quantum object: dims = [[2, 2, 2, 2], [1, 1, 1, 1]], shape = (16, 1), type = ket
        Qobj data =
        [[0.]
         [0.]
         [0.]
         [0.]
         [0.]
         [0.]
         [0.]
         [0.]
         [0.]
         [0.]
         [0.]
         [0.]
         [0.]
         [0.]
         [0.]
         [1.]]                                                                          ,
        Quantum object: dims = [[2, 2, 2, 2], [1, 1, 1, 1]], shape = (16, 1), type = ket
        Qobj data =
        [[0.]
         [0.]
         [0.]
         [0.]
         [0.]
         [0.]
         [0.]
         [0.]
         [0.]
         [0.]
         [0.]
         [0.]
         [0.]
         [1.]
         [0.]
         [0.]]                                                                          ,
        Quantum object: dims = [[2, 2, 2, 2], [1, 1, 1, 1]], shape =

## Results

For the logical graph we have:
-  -6: $|111 \rangle$
-  -4: $|101 \rangle$, $|110 \rangle$
-  +0: $|000 \rangle$
-  +2: $|100 \rangle$, $|001 \rangle$, $|010 \rangle$
-  +8: $|011 \rangle$

For the physical graph we have:
-  -12: $|1111 \rangle (\mathbf{|111 \rangle})$
-  -10: $|1101 \rangle (\mathbf{|101 \rangle})$, $|1110 \rangle(\mathbf{|110 \rangle})$
-  -4: $|1100 \rangle (\mathbf{|100 \rangle})$
-  -2: $|0110 \rangle$, $|1001 \rangle$
-  +0: $|0000 \rangle (\mathbf{|000 \rangle})$
-  +2: $|0001 \rangle (\mathbf{|001 \rangle})$, $|0010 \rangle(\mathbf{|010 \rangle})$
-  +4: $|1011 \rangle$, $|0111 \rangle$, $|1000 \rangle$, $|0100 \rangle$
-  +6: $|1010 \rangle$, $|0101 \rangle$
-  +8: $|0011 \rangle (\mathbf{|011\rangle})$